# Placeholder now
version: 0.2

env:
  git-credential-helper: yes
  MAKEFILE_PATH: "./Makefile"   # Default Makefile path, you can change this as needed

phases:
  install:
    runtime-versions:
      docker: 19
  install:
    commands:
      - git submodule init
      - git submodule update --recursive
  pre_build:
    commands:
      - git status
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - RELEASE_SHA=$(echo $CODEBUILD_SOURCE_VERSION | head -c 7)
      - BRANCH_NAME1=$(echo $CODEBUILD_WEBHOOK_BASE_REF | cut -d'/' -f 3)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - if [ -f "$MAKEFILE_PATH" ]; then make -f "$MAKEFILE_PATH" build; else echo "Makefile not found."; exit 1; fi
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - if [ -f "$MAKEFILE_PATH" ]; then make -f "$MAKEFILE_PATH" push; else echo "Makefile not found."; exit 1; fi
      - echo Writing image definitions file...
      - printf '{"ImageURI":"%s"}' > imageDetail.json
artifacts:
  files:
    - imageDetail.json
