DNS_ORG_MAPPING = {
    "lbl.gov": "Lawrence Berkeley National Laboratory (LBNL)",
    "ornl.gov": "Oak Ridge National Laboratory (ORNL)",
    "anl.gov": "Argonne National Laboratory (ANL)",
    "ameslab.gov": "Ames National Laboratory",
    "bnl.gov": "Brookhaven National Laboratory (BNL)",
    "www.pppl.gov": "Princeton Plasma Physics Laboratory (PPPL)",
    "slac.stanford.edu": "SLAC National Accelerator Laboratory",
    "pnnl.gov": "Pacific Northwest National Laboratory (PNNL)",
    "fnal.gov": "Fermi National Accelerator Laboratory (FNAL)",
    "jlab.org": "Thomas Jefferson National Accelerator Facility (TJNAF)",
    "lanl.gov": "Los Alamos National Laboratory (LANL)",
    "sandia.gov": "Sandia National Laboratories (SNL)",
    "llnl.gov": "Lawrence Livermore National Laboratory (LLNL)",
    "nrel.gov": "National Renewable Energy Laboratory (NREL)",
    "srnl.doe.gov": "Savannah River National Laboratory (SRNL)",
    "netl.doe.gov": "National Energy Technology Laboratory (NETL)",
    "inl.gov": "Idaho National Laboratory (INL)",
}
